#!/bin/bash

# Oracle/OpenJDK JRE version 1.8+ has to be present on your path
# OR in a directory called "jre" in the same directory as this script
# detect real location of this script, regardless aliases and symlinks
SCRIPT_DIR=$(dirname $0)
cd $SCRIPT_DIR
SCRIPT_DIR=$(pwd)
JAR_FILE="${SCRIPT_DIR}/kse.jar"

if [ -d "${SCRIPT_DIR}/jre" ]; then
    export LD_LIBRARY_PATH=${SCRIPT_DIR}/jre/lib:$LD_LIBRARY_PATH
    "${SCRIPT_DIR}/jre/bin/java" -jar "${JAR_FILE}" "$@"
else
    java -jar "${JAR_FILE}" "$@"
fi
